# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:42:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class GoogleApiHttpBody(BaseModel):
    contentType: Optional[str] = Field(
        None,
        description='The HTTP Content-Type header value specifying the content type of the body.',
    )
    data: Optional[str] = Field(
        None, description='The HTTP request/response body as raw binary.'
    )
    extensions: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='Application specific response metadata. Must be set in the first response for streaming APIs.',
    )


class GoogleCloudRecommendationengineV1alphaRejoinCatalogMetadata(BaseModel):
    pass


class GoogleCloudRecommendationengineV1alphaRejoinCatalogResponse(BaseModel):
    rejoinedUserEventsCount: Optional[str] = Field(
        None,
        description='Number of user events that were joined with latest catalog items.',
    )


class GoogleCloudRecommendationengineV1alphaTuningMetadata(BaseModel):
    recommendationModel: Optional[str] = Field(
        None,
        description='The resource name of the recommendation model that this tune applies to. Format: projects/{project_number}/locations/{location_id}/catalogs/{catalog_id}/eventStores/{event_store_id}/recommendationModels/{recommendation_model_id}',
    )


class GoogleCloudRecommendationengineV1alphaTuningResponse(BaseModel):
    pass


class GoogleCloudRecommendationengineV1beta1BigQuerySource(BaseModel):
    dataSchema: Optional[str] = Field(
        None,
        description='Optional. The schema to use when parsing the data from the source. Supported values for catalog imports: 1: "catalog_recommendations_ai" using https://cloud.google.com/recommendations-ai/docs/upload-catalog#json (Default for catalogItems.import) 2: "catalog_merchant_center" using https://cloud.google.com/recommendations-ai/docs/upload-catalog#mc Supported values for user event imports: 1: "user_events_recommendations_ai" using https://cloud.google.com/recommendations-ai/docs/manage-user-events#import (Default for userEvents.import) 2. "user_events_ga360" using https://support.google.com/analytics/answer/3437719?hl=en',
    )
    datasetId: Optional[str] = Field(
        None, description='Required. The BigQuery data set to copy the data from.'
    )
    gcsStagingDir: Optional[str] = Field(
        None,
        description='Optional. Intermediate Cloud Storage directory used for the import. Can be specified if one wants to have the BigQuery export to a specific Cloud Storage directory.',
    )
    projectId: Optional[str] = Field(
        None,
        description='Optional. The project id (can be project # or id) that the BigQuery source is in. If not specified, inherits the project id from the parent request.',
    )
    tableId: Optional[str] = Field(
        None, description='Required. The BigQuery table to copy the data from.'
    )


class GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy(BaseModel):
    categories: Optional[List[str]] = Field(
        None,
        description='Required. Catalog item categories. Each category should be a UTF-8 encoded string with a length limit of 2 KiB. Note that the order in the list denotes the specificity (from least to most specific).',
    )


class EventItemLevel(Enum):
    CATALOG_ITEM_LEVEL_UNSPECIFIED = 'CATALOG_ITEM_LEVEL_UNSPECIFIED'
    VARIANT = 'VARIANT'
    MASTER = 'MASTER'


class PredictItemLevel(Enum):
    CATALOG_ITEM_LEVEL_UNSPECIFIED = 'CATALOG_ITEM_LEVEL_UNSPECIFIED'
    VARIANT = 'VARIANT'
    MASTER = 'MASTER'


class GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig(BaseModel):
    eventItemLevel: Optional[EventItemLevel] = Field(
        None,
        description='Optional. Level of the catalog at which events are uploaded. See https://cloud.google.com/recommendations-ai/docs/catalog#catalog-levels for more details.',
    )
    predictItemLevel: Optional[PredictItemLevel] = Field(
        None,
        description='Optional. Level of the catalog at which predictions are made. See https://cloud.google.com/recommendations-ai/docs/catalog#catalog-levels for more details.',
    )


class GoogleCloudRecommendationengineV1beta1FeatureMapFloatList(BaseModel):
    value: Optional[List[float]] = Field(None, description='Float feature value.')


class GoogleCloudRecommendationengineV1beta1FeatureMapStringList(BaseModel):
    value: Optional[List[str]] = Field(
        None, description='String feature value with a length limit of 128 bytes.'
    )


class GoogleCloudRecommendationengineV1beta1GcsSource(BaseModel):
    inputUris: Optional[List[str]] = Field(
        None,
        description='Required. Google Cloud Storage URIs to input files. URI can be up to 2000 characters long. URIs can match the full object path (for example, `gs://bucket/directory/object.json`) or a pattern matching one or more files, such as `gs://bucket/directory/*.json`. A request can contain at most 100 files, and each file can be up to 2 GB. See [Importing catalog information](/recommendations-ai/docs/upload-catalog) for the expected file format and setup instructions.',
    )
    jsonSchema: Optional[str] = Field(
        None,
        description='Optional. The schema to use when parsing the data from the source. Supported values for catalog imports: 1: "catalog_recommendations_ai" using https://cloud.google.com/recommendations-ai/docs/upload-catalog#json (Default for catalogItems.import) 2: "catalog_merchant_center" using https://cloud.google.com/recommendations-ai/docs/upload-catalog#mc Supported values for user events imports: 1: "user_events_recommendations_ai" using https://cloud.google.com/recommendations-ai/docs/manage-user-events#import (Default for userEvents.import) 2. "user_events_ga360" using https://support.google.com/analytics/answer/3437719?hl=en',
    )


class GoogleCloudRecommendationengineV1beta1Image(BaseModel):
    height: Optional[int] = Field(
        None, description='Optional. Height of the image in number of pixels.'
    )
    uri: Optional[str] = Field(
        None, description='Required. URL of the image with a length limit of 5 KiB.'
    )
    width: Optional[int] = Field(
        None, description='Optional. Width of the image in number of pixels.'
    )


class GoogleCloudRecommendationengineV1beta1ImportErrorsConfig(BaseModel):
    gcsPrefix: Optional[str] = Field(
        None,
        description='Google Cloud Storage path for import errors. This must be an empty, existing Cloud Storage bucket. Import errors will be written to a file in this bucket, one per line, as a JSON-encoded `google.rpc.Status` message.',
    )


class GoogleCloudRecommendationengineV1beta1ImportMetadata(BaseModel):
    createTime: Optional[str] = Field(None, description='Operation create time.')
    failureCount: Optional[str] = Field(
        None, description='Count of entries that encountered errors while processing.'
    )
    operationName: Optional[str] = Field(None, description='Name of the operation.')
    requestId: Optional[str] = Field(
        None,
        description='Id of the request / operation. This is parroting back the requestId that was passed in the request.',
    )
    successCount: Optional[str] = Field(
        None, description='Count of entries that were processed successfully.'
    )
    updateTime: Optional[str] = Field(
        None,
        description='Operation last update time. If the operation is done, this is also the finish time.',
    )


class GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResult(BaseModel):
    id: Optional[str] = Field(None, description='ID of the recommended catalog item')
    itemMetadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Additional item metadata / annotations. Possible values: * `catalogItem`: JSON representation of the catalogItem. Will be set if `returnCatalogItem` is set to true in `PredictRequest.params`. * `score`: Prediction score in double value. Will be set if `returnItemScore` is set to true in `PredictRequest.params`.',
    )


class GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration(BaseModel):
    apiKey: Optional[str] = Field(None, description='The API key.')


class StockState(Enum):
    STOCK_STATE_UNSPECIFIED = 'STOCK_STATE_UNSPECIFIED'
    IN_STOCK = 'IN_STOCK'
    OUT_OF_STOCK = 'OUT_OF_STOCK'
    PREORDER = 'PREORDER'
    BACKORDER = 'BACKORDER'


class GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPrice(BaseModel):
    displayPrice: Optional[float] = Field(
        None, description='Optional. Display price of the product.'
    )
    originalPrice: Optional[float] = Field(
        None,
        description="Optional. Price of the product without any discount. If zero, by default set to be the 'displayPrice'.",
    )


class GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRange(BaseModel):
    max: Optional[float] = Field(
        None, description='Required. The maximum product price.'
    )
    min: Optional[float] = Field(
        None, description='Required. The minimum product price.'
    )


class GoogleCloudRecommendationengineV1beta1PurchaseTransaction(BaseModel):
    costs: Optional[Dict[str, float]] = Field(
        None,
        description='Optional. All the costs associated with the product. These can be manufacturing costs, shipping expenses not borne by the end user, or any other costs. Total product cost such that profit = revenue - (sum(taxes) + sum(costs)) If product_cost is not set, then profit = revenue - tax - shipping - sum(CatalogItem.costs). If CatalogItem.cost is not specified for one of the items, CatalogItem.cost based profit *cannot* be calculated for this Transaction.',
    )
    currencyCode: Optional[str] = Field(
        None,
        description='Required. Currency code. Use three-character ISO-4217 code. This field is not required if the event type is `refund`.',
    )
    id: Optional[str] = Field(
        None,
        description='Optional. The transaction ID with a length limit of 128 bytes.',
    )
    revenue: Optional[float] = Field(
        None,
        description='Required. Total revenue or grand total associated with the transaction. This value include shipping, tax, or other adjustments to total revenue that you want to include as part of your revenue calculations. This field is not required if the event type is `refund`.',
    )
    taxes: Optional[Dict[str, float]] = Field(
        None, description='Optional. All the taxes associated with the transaction.'
    )


class GoogleCloudRecommendationengineV1beta1PurgeUserEventsMetadata(BaseModel):
    createTime: Optional[str] = Field(None, description='Operation create time.')
    operationName: Optional[str] = Field(
        None, description='The ID of the request / operation.'
    )


class GoogleCloudRecommendationengineV1beta1PurgeUserEventsRequest(BaseModel):
    filter: Optional[str] = Field(
        None,
        description='Required. The filter string to specify the events to be deleted. Empty string filter is not allowed. The eligible fields for filtering are: * `eventType`: UserEvent.eventType field of type string. * `eventTime`: in ISO 8601 "zulu" format. * `visitorId`: field of type string. Specifying this will delete all events associated with a visitor. * `userId`: field of type string. Specifying this will delete all events associated with a user. Examples: * Deleting all events in a time range: `eventTime > "2012-04-23T18:25:43.511Z" eventTime < "2012-04-23T18:30:43.511Z"` * Deleting specific eventType in time range: `eventTime > "2012-04-23T18:25:43.511Z" eventType = "detail-page-view"` * Deleting all events for a specific visitor: `visitorId = "visitor1024"` The filtering fields are assumed to have an implicit AND.',
    )
    force: Optional[bool] = Field(
        None,
        description='Optional. The default value is false. Override this flag to true to actually perform the purge. If the field is not set to true, a sampling of events to be deleted will be returned.',
    )


class GoogleCloudRecommendationengineV1beta1RejoinUserEventsMetadata(BaseModel):
    pass


class UserEventRejoinScope(Enum):
    USER_EVENT_REJOIN_SCOPE_UNSPECIFIED = 'USER_EVENT_REJOIN_SCOPE_UNSPECIFIED'
    JOINED_EVENTS = 'JOINED_EVENTS'
    UNJOINED_EVENTS = 'UNJOINED_EVENTS'


class GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequest(BaseModel):
    userEventRejoinScope: Optional[UserEventRejoinScope] = Field(
        None,
        description='Required. The type of the catalog rejoin to define the scope and range of the user events to be rejoined with catalog items.',
    )


class GoogleCloudRecommendationengineV1beta1RejoinUserEventsResponse(BaseModel):
    rejoinedUserEventsCount: Optional[str] = Field(
        None,
        description='Number of user events that were joined with latest catalog items.',
    )


class EventSource(Enum):
    EVENT_SOURCE_UNSPECIFIED = 'EVENT_SOURCE_UNSPECIFIED'
    AUTOML = 'AUTOML'
    ECOMMERCE = 'ECOMMERCE'
    BATCH_UPLOAD = 'BATCH_UPLOAD'


class GoogleCloudRecommendationengineV1beta1UserEventImportSummary(BaseModel):
    joinedEventsCount: Optional[str] = Field(
        None,
        description='Count of user events imported with complete existing catalog information.',
    )
    unjoinedEventsCount: Optional[str] = Field(
        None,
        description='Count of user events imported, but with catalog information not found in the imported catalog.',
    )


class GoogleCloudRecommendationengineV1beta1UserInfo(BaseModel):
    directUserRequest: Optional[bool] = Field(
        None,
        description='Optional. Indicates if the request is made directly from the end user in which case the user_agent and ip_address fields can be populated from the HTTP request. This should *not* be set when using the javascript pixel. This flag should be set only if the API request is made directly from the end user such as a mobile app (and not if a gateway or a server is processing and pushing the user events).',
    )
    ipAddress: Optional[str] = Field(
        None,
        description='Optional. IP address of the user. This could be either IPv4 (e.g. 104.133.9.80) or IPv6 (e.g. 2001:0db8:85a3:0000:0000:8a2e:0370:7334). This should *not* be set when using the javascript pixel or if `direct_user_request` is set. Used to extract location information for personalization.',
    )
    userAgent: Optional[str] = Field(
        None,
        description='Optional. User agent as included in the HTTP header. UTF-8 encoded string with a length limit of 1 KiB. This should *not* be set when using the JavaScript pixel or if `directUserRequest` is set.',
    )
    userId: Optional[str] = Field(
        None,
        description="Optional. Unique identifier for logged-in user with a length limit of 128 bytes. Required only for logged-in users. Don't set for anonymous users. Don't set the field to the same fixed ID for different users. This mixes the event history of those users together, which results in degraded model quality.",
    )
    visitorId: Optional[str] = Field(
        None,
        description="Required. A unique identifier for tracking visitors with a length limit of 128 bytes. For example, this could be implemented with an HTTP cookie, which should be able to uniquely identify a visitor on a single device. This unique identifier should not change if the visitor logs in or out of the website. Maximum length 128 bytes. Cannot be empty. Don't set the field to the same fixed ID for different users. This mixes the event history of those users together, which results in degraded model quality.",
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleRpcStatus(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleCloudRecommendationengineV1beta1Catalog(BaseModel):
    catalogItemLevelConfig: Optional[
        GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig
    ] = Field(None, description='Required. The catalog item level configuration.')
    defaultEventStoreId: Optional[str] = Field(
        None, description='Required. The ID of the default event store.'
    )
    displayName: Optional[str] = Field(
        None, description='Required. The catalog display name.'
    )
    name: Optional[str] = Field(
        None, description='The fully qualified resource name of the catalog.'
    )


class GoogleCloudRecommendationengineV1beta1CreatePredictionApiKeyRegistrationRequest(
    BaseModel
):
    predictionApiKeyRegistration: Optional[
        GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration
    ] = Field(None, description='Required. The prediction API key registration.')


class GoogleCloudRecommendationengineV1beta1FeatureMap(BaseModel):
    categoricalFeatures: Optional[
        Dict[str, GoogleCloudRecommendationengineV1beta1FeatureMapStringList]
    ] = Field(
        None,
        description='Categorical features that can take on one of a limited number of possible values. Some examples would be the brand/maker of a product, or country of a customer. Feature names and values must be UTF-8 encoded strings. For example: `{ "colors": {"value": ["yellow", "green"]}, "sizes": {"value":["S", "M"]}`',
    )
    numericalFeatures: Optional[
        Dict[str, GoogleCloudRecommendationengineV1beta1FeatureMapFloatList]
    ] = Field(
        None,
        description='Numerical features. Some examples would be the height/weight of a product, or age of a customer. Feature names must be UTF-8 encoded strings. For example: `{ "lengths_cm": {"value":[2.3, 15.4]}, "heights_cm": {"value":[8.1, 6.4]} }`',
    )


class GoogleCloudRecommendationengineV1beta1ImportCatalogItemsResponse(BaseModel):
    errorSamples: Optional[List[GoogleRpcStatus]] = Field(
        None, description='A sample of errors encountered while processing the request.'
    )
    errorsConfig: Optional[GoogleCloudRecommendationengineV1beta1ImportErrorsConfig] = (
        Field(
            None,
            description='Echoes the destination for the complete errors in the request if set.',
        )
    )


class GoogleCloudRecommendationengineV1beta1ImportUserEventsResponse(BaseModel):
    errorSamples: Optional[List[GoogleRpcStatus]] = Field(
        None, description='A sample of errors encountered while processing the request.'
    )
    errorsConfig: Optional[GoogleCloudRecommendationengineV1beta1ImportErrorsConfig] = (
        Field(
            None,
            description='Echoes the destination for the complete errors if this field was set in the request.',
        )
    )
    importSummary: Optional[
        GoogleCloudRecommendationengineV1beta1UserEventImportSummary
    ] = Field(None, description='Aggregated statistics of user event import status.')


class GoogleCloudRecommendationengineV1beta1ListCatalogsResponse(BaseModel):
    catalogs: Optional[List[GoogleCloudRecommendationengineV1beta1Catalog]] = Field(
        None, description="Output only. All the customer's catalogs."
    )
    nextPageToken: Optional[str] = Field(
        None, description='Pagination token, if not returned indicates the last page.'
    )


class GoogleCloudRecommendationengineV1beta1ListPredictionApiKeyRegistrationsResponse(
    BaseModel
):
    nextPageToken: Optional[str] = Field(
        None,
        description="If empty, the list is complete. If nonempty, pass the token to the next request's `ListPredictionApiKeysRegistrationsRequest.pageToken`.",
    )
    predictionApiKeyRegistrations: Optional[
        List[GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration]
    ] = Field(None, description='The list of registered API keys.')


class GoogleCloudRecommendationengineV1beta1PredictResponse(BaseModel):
    dryRun: Optional[bool] = Field(
        None, description='True if the dryRun property was set in the request.'
    )
    itemsMissingInCatalog: Optional[List[str]] = Field(
        None,
        description='IDs of items in the request that were missing from the catalog.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None, description='Additional domain specific prediction response metadata.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description="If empty, the list is complete. If nonempty, the token to pass to the next request's PredictRequest.page_token.",
    )
    recommendationToken: Optional[str] = Field(
        None,
        description='A unique recommendation token. This should be included in the user event logs resulting from this recommendation, which enables accurate attribution of recommendation model performance.',
    )
    results: Optional[
        List[GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResult]
    ] = Field(
        None,
        description='A list of recommended items. The order represents the ranking (from the most relevant item to the least).',
    )


class GoogleCloudRecommendationengineV1beta1ProductCatalogItem(BaseModel):
    availableQuantity: Optional[str] = Field(
        None, description='Optional. The available quantity of the item.'
    )
    canonicalProductUri: Optional[str] = Field(
        None,
        description='Optional. Canonical URL directly linking to the item detail page with a length limit of 5 KiB..',
    )
    costs: Optional[Dict[str, float]] = Field(
        None,
        description='Optional. A map to pass the costs associated with the product. For example: {"manufacturing": 45.5} The profit of selling this item is computed like so: * If \'exactPrice\' is provided, profit = displayPrice - sum(costs) * If \'priceRange\' is provided, profit = minPrice - sum(costs)',
    )
    currencyCode: Optional[str] = Field(
        None,
        description='Optional. Only required if the price is set. Currency code for price/costs. Use three-character ISO-4217 code.',
    )
    exactPrice: Optional[
        GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPrice
    ] = Field(None, description='Optional. The exact product price.')
    images: Optional[List[GoogleCloudRecommendationengineV1beta1Image]] = Field(
        None, description='Optional. Product images for the catalog item.'
    )
    priceRange: Optional[
        GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRange
    ] = Field(None, description='Optional. The product price range.')
    stockState: Optional[StockState] = Field(
        None,
        description='Optional. Online stock state of the catalog item. Default is `IN_STOCK`.',
    )


class GoogleCloudRecommendationengineV1beta1ProductDetail(BaseModel):
    availableQuantity: Optional[int] = Field(
        None,
        description='Optional. Quantity of the products in stock when a user event happens. Optional. If provided, this overrides the available quantity in Catalog for this event. and can only be set if `stock_status` is set to `IN_STOCK`. Note that if an item is out of stock, you must set the `stock_state` field to be `OUT_OF_STOCK`. Leaving this field unspecified / as zero is not sufficient to mark the item out of stock.',
    )
    currencyCode: Optional[str] = Field(
        None,
        description='Optional. Currency code for price/costs. Use three-character ISO-4217 code. Required only if originalPrice or displayPrice is set.',
    )
    displayPrice: Optional[float] = Field(
        None,
        description='Optional. Display price of the product (e.g. discounted price). If provided, this will override the display price in Catalog for this product.',
    )
    id: Optional[str] = Field(
        None,
        description='Required. Catalog item ID. UTF-8 encoded string with a length limit of 128 characters.',
    )
    itemAttributes: Optional[GoogleCloudRecommendationengineV1beta1FeatureMap] = Field(
        None,
        description='Optional. Extra features associated with a product in the user event.',
    )
    originalPrice: Optional[float] = Field(
        None,
        description='Optional. Original price of the product. If provided, this will override the original price in Catalog for this product.',
    )
    quantity: Optional[int] = Field(
        None,
        description='Optional. Quantity of the product associated with the user event. For example, this field will be 2 if two products are added to the shopping cart for `add-to-cart` event. Required for `add-to-cart`, `add-to-list`, `remove-from-cart`, `checkout-start`, `purchase-complete`, `refund` event types.',
    )
    stockState: Optional[StockState] = Field(
        None,
        description='Optional. Item stock state. If provided, this overrides the stock state in Catalog for items in this event.',
    )


class GoogleCloudRecommendationengineV1beta1ProductEventDetail(BaseModel):
    cartId: Optional[str] = Field(
        None,
        description='Optional. The id or name of the associated shopping cart. This id is used to associate multiple items added or present in the cart before purchase. This can only be set for `add-to-cart`, `remove-from-cart`, `checkout-start`, `purchase-complete`, or `shopping-cart-page-view` events.',
    )
    listId: Optional[str] = Field(
        None,
        description='Required for `add-to-list` and `remove-from-list` events. The id or name of the list that the item is being added to or removed from. Other event types should not set this field.',
    )
    pageCategories: Optional[
        List[GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy]
    ] = Field(
        None,
        description='Required for `category-page-view` events. At least one of search_query or page_categories is required for `search` events. Other event types should not set this field. The categories associated with a category page. Category pages include special pages such as sales or promotions. For instance, a special sale page may have the category hierarchy: categories : ["Sales", "2017 Black Friday Deals"].',
    )
    productDetails: Optional[
        List[GoogleCloudRecommendationengineV1beta1ProductDetail]
    ] = Field(
        None,
        description="The main product details related to the event. This field is required for the following event types: * `add-to-cart` * `add-to-list` * `checkout-start` * `detail-page-view` * `purchase-complete` * `refund` * `remove-from-cart` * `remove-from-list` This field is optional for the following event types: * `page-visit` * `shopping-cart-page-view` - note that 'product_details' should be set for this unless the shopping cart is empty. * `search` (highly encouraged) In a `search` event, this field represents the products returned to the end user on the current page (the end user may have not finished broswing the whole page yet). When a new page is returned to the end user, after pagination/filtering/ordering even for the same query, a new SEARCH event with different product_details is desired. The end user may have not finished broswing the whole page yet. This field is not allowed for the following event types: * `category-page-view` * `home-page-view`",
    )
    purchaseTransaction: Optional[
        GoogleCloudRecommendationengineV1beta1PurchaseTransaction
    ] = Field(
        None,
        description='Optional. A transaction represents the entire purchase transaction. Required for `purchase-complete` events. Optional for `checkout-start` events. Other event types should not set this field.',
    )
    searchQuery: Optional[str] = Field(
        None,
        description="At least one of search_query or page_categories is required for `search` events. Other event types should not set this field. The user's search query as UTF-8 encoded text with a length limit of 5 KiB.",
    )


class GoogleLongrunningOperation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[GoogleRpcStatus] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class GoogleCloudRecommendationengineV1beta1CatalogItem(BaseModel):
    categoryHierarchies: Optional[
        List[GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy]
    ] = Field(
        None,
        description='Required. Catalog item categories. This field is repeated for supporting one catalog item belonging to several parallel category hierarchies. For example, if a shoes product belongs to both ["Shoes & Accessories" -> "Shoes"] and ["Sports & Fitness" -> "Athletic Clothing" -> "Shoes"], it could be represented as: "categoryHierarchies": [ { "categories": ["Shoes & Accessories", "Shoes"]}, { "categories": ["Sports & Fitness", "Athletic Clothing", "Shoes"] } ]',
    )
    description: Optional[str] = Field(
        None,
        description='Optional. Catalog item description. UTF-8 encoded string with a length limit of 5 KiB.',
    )
    id: Optional[str] = Field(
        None,
        description='Required. Catalog item identifier. UTF-8 encoded string with a length limit of 128 bytes. This id must be unique among all catalog items within the same catalog. It should also be used when logging user events in order for the user events to be joined with the Catalog.',
    )
    itemAttributes: Optional[GoogleCloudRecommendationengineV1beta1FeatureMap] = Field(
        None,
        description='Optional. Highly encouraged. Extra catalog item attributes to be included in the recommendation model. For example, for retail products, this could include the store name, vendor, style, color, etc. These are very strong signals for recommendation model, thus we highly recommend providing the item attributes here.',
    )
    itemGroupId: Optional[str] = Field(
        None,
        description='Optional. Variant group identifier for prediction results. UTF-8 encoded string with a length limit of 128 bytes. This field must be enabled before it can be used. [Learn more](/recommendations-ai/docs/catalog#item-group-id).',
    )
    languageCode: Optional[str] = Field(
        None,
        description='Optional. Deprecated. The model automatically detects the text language. Your catalog can include text in different languages, but duplicating catalog items to provide text in multiple languages can result in degraded model performance.',
    )
    productMetadata: Optional[
        GoogleCloudRecommendationengineV1beta1ProductCatalogItem
    ] = Field(None, description='Optional. Metadata specific to retail products.')
    tags: Optional[List[str]] = Field(
        None,
        description='Optional. Filtering tags associated with the catalog item. Each tag should be a UTF-8 encoded string with a length limit of 1 KiB. This tag can be used for filtering recommendation results by passing the tag as part of the predict request filter.',
    )
    title: Optional[str] = Field(
        None,
        description='Required. Catalog item title. UTF-8 encoded string with a length limit of 1 KiB.',
    )


class GoogleCloudRecommendationengineV1beta1EventDetail(BaseModel):
    eventAttributes: Optional[GoogleCloudRecommendationengineV1beta1FeatureMap] = Field(
        None,
        description='Optional. Extra user event features to include in the recommendation model. For product recommendation, an example of extra user information is traffic_channel, i.e. how user arrives at the site. Users can arrive at the site by coming to the site directly, or coming through Google search, and etc.',
    )
    experimentIds: Optional[List[str]] = Field(
        None,
        description='Optional. A list of identifiers for the independent experiment groups this user event belongs to. This is used to distinguish between user events associated with different experiment setups (e.g. using Recommendation Engine system, using different recommendation models).',
    )
    pageViewId: Optional[str] = Field(
        None,
        description='Optional. A unique id of a web page view. This should be kept the same for all user events triggered from the same pageview. For example, an item detail page view could trigger multiple events as the user is browsing the page. The `pageViewId` property should be kept the same for all these events so that they can be grouped together properly. This `pageViewId` will be automatically generated if using the JavaScript pixel.',
    )
    recommendationToken: Optional[str] = Field(
        None,
        description="Optional. Recommendation token included in the recommendation prediction response. This field enables accurate attribution of recommendation model performance. This token enables us to accurately attribute page view or purchase back to the event and the particular predict response containing this clicked/purchased item. If user clicks on product K in the recommendation results, pass the `PredictResponse.recommendationToken` property as a url parameter to product K's page. When recording events on product K's page, log the PredictResponse.recommendation_token to this field. Optional, but highly encouraged for user events that are the result of a recommendation prediction query.",
    )
    referrerUri: Optional[str] = Field(
        None,
        description='Optional. The referrer url of the current page. When using the JavaScript pixel, this value is filled in automatically.',
    )
    uri: Optional[str] = Field(
        None,
        description="Optional. Complete url (window.location.href) of the user's current page. When using the JavaScript pixel, this value is filled in automatically. Maximum length 5KB.",
    )


class GoogleCloudRecommendationengineV1beta1ListCatalogItemsResponse(BaseModel):
    catalogItems: Optional[List[GoogleCloudRecommendationengineV1beta1CatalogItem]] = (
        Field(None, description='The catalog items.')
    )
    nextPageToken: Optional[str] = Field(
        None,
        description="If empty, the list is complete. If nonempty, the token to pass to the next request's ListCatalogItemRequest.page_token.",
    )


class GoogleCloudRecommendationengineV1beta1UserEvent(BaseModel):
    eventDetail: Optional[GoogleCloudRecommendationengineV1beta1EventDetail] = Field(
        None,
        description='Optional. User event detailed information common across different recommendation types.',
    )
    eventSource: Optional[EventSource] = Field(
        None,
        description='Optional. This field should *not* be set when using JavaScript pixel or the Recommendations AI Tag. Defaults to `EVENT_SOURCE_UNSPECIFIED`.',
    )
    eventTime: Optional[str] = Field(
        None,
        description='Optional. Only required for ImportUserEvents method. Timestamp of user event created.',
    )
    eventType: Optional[str] = Field(
        None,
        description='Required. User event type. Allowed values are: * `add-to-cart` Products being added to cart. * `add-to-list` Items being added to a list (shopping list, favorites etc). * `category-page-view` Special pages such as sale or promotion pages viewed. * `checkout-start` User starting a checkout process. * `detail-page-view` Products detail page viewed. * `home-page-view` Homepage viewed. * `page-visit` Generic page visits not included in the event types above. * `purchase-complete` User finishing a purchase. * `refund` Purchased items being refunded or returned. * `remove-from-cart` Products being removed from cart. * `remove-from-list` Items being removed from a list. * `search` Product search. * `shopping-cart-page-view` User viewing a shopping cart. * `impression` List of items displayed. Used by Google Tag Manager.',
    )
    productEventDetail: Optional[
        GoogleCloudRecommendationengineV1beta1ProductEventDetail
    ] = Field(
        None,
        description="Optional. Retail product specific user event metadata. This field is required for the following event types: * `add-to-cart` * `add-to-list` * `category-page-view` * `checkout-start` * `detail-page-view` * `purchase-complete` * `refund` * `remove-from-cart` * `remove-from-list` * `search` This field is optional for the following event types: * `page-visit` * `shopping-cart-page-view` - note that 'product_event_detail' should be set for this unless the shopping cart is empty. This field is not allowed for the following event types: * `home-page-view`",
    )
    userInfo: Optional[GoogleCloudRecommendationengineV1beta1UserInfo] = Field(
        None, description='Required. User information.'
    )


class GoogleCloudRecommendationengineV1beta1UserEventInlineSource(BaseModel):
    userEvents: Optional[List[GoogleCloudRecommendationengineV1beta1UserEvent]] = Field(
        None,
        description='Optional. A list of user events to import. Recommended max of 10k items.',
    )


class GoogleLongrunningListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[GoogleLongrunningOperation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class GoogleCloudRecommendationengineV1beta1CatalogInlineSource(BaseModel):
    catalogItems: Optional[List[GoogleCloudRecommendationengineV1beta1CatalogItem]] = (
        Field(
            None,
            description='Optional. A list of catalog items to update/create. Recommended max of 10k items.',
        )
    )


class GoogleCloudRecommendationengineV1beta1InputConfig(BaseModel):
    bigQuerySource: Optional[GoogleCloudRecommendationengineV1beta1BigQuerySource] = (
        Field(None, description='BigQuery input source.')
    )
    catalogInlineSource: Optional[
        GoogleCloudRecommendationengineV1beta1CatalogInlineSource
    ] = Field(
        None, description='The Inline source for the input content for Catalog items.'
    )
    gcsSource: Optional[GoogleCloudRecommendationengineV1beta1GcsSource] = Field(
        None, description='Google Cloud Storage location for the input content.'
    )
    userEventInlineSource: Optional[
        GoogleCloudRecommendationengineV1beta1UserEventInlineSource
    ] = Field(
        None, description='The Inline source for the input content for UserEvents.'
    )


class GoogleCloudRecommendationengineV1beta1ListUserEventsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description="If empty, the list is complete. If nonempty, the token to pass to the next request's ListUserEvents.page_token.",
    )
    userEvents: Optional[List[GoogleCloudRecommendationengineV1beta1UserEvent]] = Field(
        None, description='The user events.'
    )


class GoogleCloudRecommendationengineV1beta1PredictRequest(BaseModel):
    dryRun: Optional[bool] = Field(
        None,
        description='Optional. Use dryRun mode for this prediction query. If set to true, a fake model will be used that returns arbitrary catalog items. Note that the dryRun mode should only be used for testing the API, or if the model is not ready.',
    )
    filter: Optional[str] = Field(
        None,
        description='Optional. Filter for restricting prediction results. Accepts values for tags and the `filterOutOfStockItems` flag. * Tag expressions. Restricts predictions to items that match all of the specified tags. Boolean operators `OR` and `NOT` are supported if the expression is enclosed in parentheses, and must be separated from the tag values by a space. `-"tagA"` is also supported and is equivalent to `NOT "tagA"`. Tag values must be double quoted UTF-8 encoded strings with a size limit of 1 KiB. * filterOutOfStockItems. Restricts predictions to items that do not have a stockState value of OUT_OF_STOCK. Examples: * tag=("Red" OR "Blue") tag="New-Arrival" tag=(NOT "promotional") * filterOutOfStockItems tag=(-"promotional") * filterOutOfStockItems If your filter blocks all prediction results, nothing will be returned. If you want generic (unfiltered) popular items to be returned instead, set `strictFiltering` to false in `PredictRequest.params`.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. The labels for the predict request. * Label keys can contain lowercase letters, digits and hyphens, must start with a letter, and must end with a letter or digit. * Non-zero label values can contain lowercase letters, digits and hyphens, must start with a letter, and must end with a letter or digit. * No more than 64 labels can be associated with a given request. See https://goo.gl/xmQnxf for more information on and examples of labels.',
    )
    pageSize: Optional[int] = Field(
        None,
        description='Optional. Maximum number of results to return per page. Set this property to the number of prediction results required. If zero, the service will choose a reasonable default.',
    )
    pageToken: Optional[str] = Field(
        None, description='Optional. The previous PredictResponse.next_page_token.'
    )
    params: Optional[Dict[str, Any]] = Field(
        None,
        description="Optional. Additional domain specific parameters for the predictions. Allowed values: * `returnCatalogItem`: Boolean. If set to true, the associated catalogItem object will be returned in the `PredictResponse.PredictionResult.itemMetadata` object in the method response. * `returnItemScore`: Boolean. If set to true, the prediction 'score' corresponding to each returned item will be set in the `metadata` field in the prediction response. The given 'score' indicates the probability of an item being clicked/purchased given the user's context and history. * `strictFiltering`: Boolean. True by default. If set to false, the service will return generic (unfiltered) popular items instead of empty if your filter blocks all prediction results. * `priceRerankLevel`: String. Default empty. If set to be non-empty, then it needs to be one of {'no-price-reranking', 'low-price-reranking', 'medium-price-reranking', 'high-price-reranking'}. This gives request level control and adjust prediction results based on product price. * `diversityLevel`: String. Default empty. If set to be non-empty, then it needs to be one of {'no-diversity', 'low-diversity', 'medium-diversity', 'high-diversity', 'auto-diversity'}. This gives request level control and adjust prediction results based on product category.",
    )
    userEvent: Optional[GoogleCloudRecommendationengineV1beta1UserEvent] = Field(
        None,
        description="Required. Context about the user, what they are looking at and what action they took to trigger the predict request. Note that this user event detail won't be ingested to userEvent logs. Thus, a separate userEvent write request is required for event logging. Don't set UserInfo.visitor_id or UserInfo.user_id to the same fixed ID for different users. If you are trying to receive non-personalized recommendations (not recommended; this can negatively impact model performance), instead set UserInfo.visitor_id to a random unique ID and leave UserInfo.user_id unset.",
    )


class GoogleCloudRecommendationengineV1beta1PurgeUserEventsResponse(BaseModel):
    purgedEventsCount: Optional[str] = Field(
        None,
        description='The total count of events purged as a result of the operation.',
    )
    userEventsSample: Optional[
        List[GoogleCloudRecommendationengineV1beta1UserEvent]
    ] = Field(
        None,
        description='A sampling of events deleted (or will be deleted) depending on the `force` property in the request. Max of 500 items will be returned.',
    )


class GoogleCloudRecommendationengineV1beta1ImportCatalogItemsRequest(BaseModel):
    errorsConfig: Optional[GoogleCloudRecommendationengineV1beta1ImportErrorsConfig] = (
        Field(
            None,
            description='Optional. The desired location of errors incurred during the Import.',
        )
    )
    inputConfig: Optional[GoogleCloudRecommendationengineV1beta1InputConfig] = Field(
        None, description='Required. The desired input location of the data.'
    )
    requestId: Optional[str] = Field(
        None,
        description='Optional. Unique identifier provided by client, within the ancestor dataset scope. Ensures idempotency and used for request deduplication. Server-generated if unspecified. Up to 128 characters long. This is returned as google.longrunning.Operation.name in the response.',
    )
    updateMask: Optional[str] = Field(
        None,
        description="Optional. Indicates which fields in the provided imported 'items' to update. If not set, will by default update all fields.",
    )


class GoogleCloudRecommendationengineV1beta1ImportUserEventsRequest(BaseModel):
    errorsConfig: Optional[GoogleCloudRecommendationengineV1beta1ImportErrorsConfig] = (
        Field(
            None,
            description='Optional. The desired location of errors incurred during the Import.',
        )
    )
    inputConfig: Optional[GoogleCloudRecommendationengineV1beta1InputConfig] = Field(
        None, description='Required. The desired input location of the data.'
    )
    requestId: Optional[str] = Field(
        None,
        description='Optional. Unique identifier provided by client, within the ancestor dataset scope. Ensures idempotency for expensive long running operations. Server-generated if unspecified. Up to 128 characters long. This is returned as google.longrunning.Operation.name in the response. Note that this field must not be set if the desired input config is catalog_inline_source.',
    )
